/**
 * GENERATED by scripts/generate-tolbi-ai-art.mjs — do not edit by hand.
 * Run `npm run tolbi-ai-art` after changing scripts/tolbi-ai-raw/.
 *
 * Source: Figma Sprint 18 (`Dpy2nP7IFnnmaPh9bBSOaq`), page « Tolbi AI — retenu,
 * vers le paquet » — `TolbiAI/Étincelle` (node 2341:12352), variant
 * `Taille=48, État=Repos, Petite étincelle=Avec` (node 2341:12050).
 * Every other variant is this drawing scaled (ADR-0056).
 *
 * No colour lives here: the inks are bound in the component, to the primitives
 * Figma binds them to (brand/500 for the leaves, accent/400 for the spark).
 */

/** The drawing's grid — 48 is its native size, every other rung a scale of it. */
export const viewBox = '0 0 48 48'

/** The four leaves, in the order the light goes round: from the west, clockwise. */
export const leaves = [
  { direction: 'west', d: 'M6 23.9999C10.08 22.6399 13.6 21.3599 16.24 21.3599C18.72 21.3599 20.48 22.5599 21.52 23.9999C20.48 25.4399 18.72 26.6399 16.24 26.6399C13.6 26.6399 10.08 25.3599 6 23.9999Z' },
  { direction: 'north', d: 'M24 1.5C25.7 6.6 27.3 11 27.3 14.3C27.3 17.4 25.8 19.6 24 20.9C22.2 19.6 20.7 17.4 20.7 14.3C20.7 11 22.3 6.6 24 1.5Z' },
  { direction: 'east', d: 'M42 23.9999C37.92 25.3599 34.4 26.6399 31.76 26.6399C29.28 26.6399 27.52 25.4399 26.48 23.9999C27.52 22.5599 29.28 21.3599 31.76 21.3599C34.4 21.3599 37.92 22.6399 42 23.9999Z' },
  { direction: 'south', d: 'M24 46.5001C22.3 41.4001 20.7 37.0001 20.7 33.7001C20.7 30.6001 22.2 28.4001 24 27.1001C25.8 28.4001 27.3 30.6001 27.3 33.7001C27.3 37.0001 25.7 41.4001 24 46.5001Z' },
] as const

/** The small spark — the only yellow in the drawing. */
export const spark = 'M40.6 1C41.12 5.16 42.42 6.76 45.8 7.4C42.42 8.04 41.12 9.64 40.6 13.8C40.08 9.64 38.78 8.04 35.4 7.4C38.78 6.76 40.08 5.16 40.6 1Z'

export type TolbiAiSparkLeaf = typeof leaves[number]['direction']
