/**
 * Generates components/Icon/icons/*.vue and components/Icon/registry.ts from
 * the real Lucide source (`lucide-static`).
 *
 * The icon set is NOT "all of Lucide" — it is the exact subset published in the
 * Figma frame `Icons/Lucide` (Foundational Visual Identity, node 31:2), listed
 * in icons.manifest.txt next to this script. Keep that file as the source of
 * truth: add a name there, re-run `npm run icons`, and the component set and
 * registry follow.
 *
 *   npm run icons
 *
 * Lucide is ISC licensed — see LICENSE-lucide next to the generated icons.
 */
import { readFileSync, writeFileSync, readdirSync, rmSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const LUCIDE = join(ROOT, 'node_modules/lucide-static/icons')
const OUT_DIR = join(ROOT, 'components/Icon/icons')
const REGISTRY = join(ROOT, 'components/Icon/registry.ts')
const MANIFEST = join(HERE, 'icons.manifest.txt')

const lucideVersion = JSON.parse(
  readFileSync(join(ROOT, 'node_modules/lucide-static/package.json'), 'utf8'),
).version

const names = readFileSync(MANIFEST, 'utf8')
  .split('\n')
  .map(l => l.trim())
  .filter(l => l && !l.startsWith('#'))
  .sort()

const unique = [...new Set(names)]
if (unique.length !== names.length) {
  throw new Error(`icons.manifest.txt has ${names.length - unique.length} duplicate name(s)`)
}

const missing = names.filter(n => {
  try { readFileSync(join(LUCIDE, `${n}.svg`)); return false } catch { return true }
})
if (missing.length) {
  throw new Error(
    `Not in lucide-static@${lucideVersion}: ${missing.join(', ')}\n` +
    `Check the spelling against https://lucide.dev/icons/ — Lucide renames icons between majors.`,
  )
}

const pascal = n => n.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('')

/** Pull the inner shapes out of a Lucide SVG, dropping its wrapper. */
function innerShapes(svg) {
  const open = svg.indexOf('>', svg.indexOf('<svg'))
  const close = svg.lastIndexOf('</svg>')
  return svg
    .slice(open + 1, close)
    .split('\n')
    .map(l => l.trim())
    .filter(Boolean)
}

// Rebuild the directory so removing a name from the manifest removes its file.
rmSync(OUT_DIR, { recursive: true, force: true })
mkdirSync(OUT_DIR, { recursive: true })

for (const name of names) {
  const shapes = innerShapes(readFileSync(join(LUCIDE, `${name}.svg`), 'utf8'))
  // No width/height: Icon.vue owns sizing via its `size` prop. Stroke
  // presentation sits on the <svg> so the shapes inherit it, as Lucide does.
  const vue = `<template>
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    xmlns="http://www.w3.org/2000/svg"
  >
${shapes.map(s => `    ${s}`).join('\n')}
  </svg>
</template>
`
  writeFileSync(join(OUT_DIR, `${name}.vue`), vue)
}

const pad = Math.max(...names.map(n => pascal(n).length))
const padKey = Math.max(...names.map(n => n.length)) + 3

const registry = `/**
 * GENERATED by scripts/generate-icons.mjs — do not edit by hand.
 * Run \`npm run icons\` after changing scripts/icons.manifest.txt.
 *
 * Source: Lucide ${lucideVersion} (ISC). The subset matches the Figma frame
 * \`Icons/Lucide\` in Foundational Visual Identity (node 31:2).
 */
${names.map(n => `import ${pascal(n).padEnd(pad)} from './icons/${n}.vue'`).join('\n')}

export const icons = {
${names.map(n => `  ${`'${n}':`.padEnd(padKey)} ${pascal(n)},`).join('\n')}
} as const

export type IconName = keyof typeof icons
`

writeFileSync(REGISTRY, registry)

writeFileSync(join(ROOT, 'components/Icon/LICENSE-lucide'), `The icons in ./icons/ are generated from Lucide (https://lucide.dev), used
under the ISC license reproduced below. Generated from lucide-static@${lucideVersion}.

ISC License

Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of
Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors
2022.

Permission to use, copy, modify, and/or distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright notice
and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
`)

console.log(`${names.length} icons generated from lucide-static@${lucideVersion}`)
console.log(`  ${readdirSync(OUT_DIR).length} files in components/Icon/icons/`)
