/**
 * GENERATED by scripts/generate-module-art.mjs — do not edit by hand.
 * Run `npm run module-art` after changing scripts/module-art-raw/.
 *
 * Source: Figma `00 — Core Brand Visual Identity` —
 *   Module illustration (node 9945:197) → the primitive artwork
 *   Modules logos      (node 9892:11717) → the same artwork on its tile
 */
import IllustrationCarbone from './art/illustration/carbone.vue'
import IllustrationSource from './art/illustration/source.vue'
import IllustrationCall from './art/illustration/call.vue'
import IllustrationScan from './art/illustration/scan.vue'
import IllustrationData from './art/illustration/data.vue'
import IllustrationId from './art/illustration/id.vue'
import IllustrationReddPlus from './art/illustration/redd-plus.vue'
import IllustrationForest from './art/illustration/forest.vue'
import IllustrationSurvey from './art/illustration/survey.vue'
import IllustrationYield from './art/illustration/yield.vue'
import IllustrationTrace from './art/illustration/trace.vue'
import LogoCarbone from './art/logo/carbone.vue'
import LogoSource from './art/logo/source.vue'
import LogoCall from './art/logo/call.vue'
import LogoScan from './art/logo/scan.vue'
import LogoData from './art/logo/data.vue'
import LogoId from './art/logo/id.vue'
import LogoReddPlus from './art/logo/redd-plus.vue'
import LogoForest from './art/logo/forest.vue'
import LogoSurvey from './art/logo/survey.vue'
import LogoYield from './art/logo/yield.vue'
import LogoTrace from './art/logo/trace.vue'

/** The raw artwork, as drawn. The primitive. */
export const illustrations = {
  'Carbone': IllustrationCarbone,
  'Source': IllustrationSource,
  'Call': IllustrationCall,
  'Scan': IllustrationScan,
  'Data': IllustrationData,
  'ID': IllustrationId,
  'Redd+': IllustrationReddPlus,
  'Forest': IllustrationForest,
  'Survey': IllustrationSurvey,
  'Yield': IllustrationYield,
  'Trace': IllustrationTrace,
} as const

/** The artwork on its rounded tile — what product surfaces consume. */
export const logos = {
  'Carbone': LogoCarbone,
  'Source': LogoSource,
  'Call': LogoCall,
  'Scan': LogoScan,
  'Data': LogoData,
  'ID': LogoId,
  'Redd+': LogoReddPlus,
  'Forest': LogoForest,
  'Survey': LogoSurvey,
  'Yield': LogoYield,
  'Trace': LogoTrace,
} as const

export const moduleNames = ['Carbone', 'Source', 'Call', 'Scan', 'Data', 'ID', 'Redd+', 'Forest', 'Survey', 'Yield', 'Trace'] as const

export type ModuleName = typeof moduleNames[number]
export type ModuleVariant = 'illustration' | 'logo'
