/**
 * GENERATED by scripts/generate-icons.mjs — do not edit by hand.
 * Run `npm run icons` after changing scripts/icons.manifest.txt.
 *
 * Source: Lucide 1.34.0 (ISC). The subset matches the Figma frame
 * `Icons/Lucide` in Foundational Visual Identity (node 31:2).
 */
import AlarmClock          from './icons/alarm-clock.vue'
import Archive             from './icons/archive.vue'
import ArrowDown           from './icons/arrow-down.vue'
import ArrowDownLeft       from './icons/arrow-down-left.vue'
import ArrowDownRight      from './icons/arrow-down-right.vue'
import ArrowDownWideNarrow from './icons/arrow-down-wide-narrow.vue'
import ArrowLeft           from './icons/arrow-left.vue'
import ArrowLeftRight      from './icons/arrow-left-right.vue'
import ArrowRight          from './icons/arrow-right.vue'
import ArrowUp             from './icons/arrow-up.vue'
import ArrowUpDown         from './icons/arrow-up-down.vue'
import ArrowUpLeft         from './icons/arrow-up-left.vue'
import ArrowUpNarrowWide   from './icons/arrow-up-narrow-wide.vue'
import ArrowUpRight        from './icons/arrow-up-right.vue'
import BadgeCheck          from './icons/badge-check.vue'
import Ban                 from './icons/ban.vue'
import Banknote            from './icons/banknote.vue'
import Bell                from './icons/bell.vue'
import BellOff             from './icons/bell-off.vue'
import BookCheck           from './icons/book-check.vue'
import BookOpen            from './icons/book-open.vue'
import Box                 from './icons/box.vue'
import Braces              from './icons/braces.vue'
import Bug                 from './icons/bug.vue'
import Building            from './icons/building.vue'
import Building2           from './icons/building-2.vue'
import Calendar            from './icons/calendar.vue'
import CalendarDays        from './icons/calendar-days.vue'
import CalendarRange       from './icons/calendar-range.vue'
import Camera              from './icons/camera.vue'
import ChartColumn         from './icons/chart-column.vue'
import ChartLine           from './icons/chart-line.vue'
import ChartPie            from './icons/chart-pie.vue'
import Check               from './icons/check.vue'
import ChevronDown         from './icons/chevron-down.vue'
import ChevronLeft         from './icons/chevron-left.vue'
import ChevronRight        from './icons/chevron-right.vue'
import ChevronUp           from './icons/chevron-up.vue'
import ChevronsLeft        from './icons/chevrons-left.vue'
import ChevronsRight       from './icons/chevrons-right.vue'
import ChevronsUpDown      from './icons/chevrons-up-down.vue'
import Circle              from './icons/circle.vue'
import CircleAlert         from './icons/circle-alert.vue'
import CircleCheck         from './icons/circle-check.vue'
import CircleCheckBig      from './icons/circle-check-big.vue'
import CircleMinus         from './icons/circle-minus.vue'
import CirclePlay          from './icons/circle-play.vue'
import CirclePlus          from './icons/circle-plus.vue'
import CircleQuestionMark  from './icons/circle-question-mark.vue'
import CircleUser          from './icons/circle-user.vue'
import CircleX             from './icons/circle-x.vue'
import Clipboard           from './icons/clipboard.vue'
import ClipboardCheck      from './icons/clipboard-check.vue'
import ClipboardList       from './icons/clipboard-list.vue'
import Clock               from './icons/clock.vue'
import CloudDownload       from './icons/cloud-download.vue'
import CloudOff            from './icons/cloud-off.vue'
import CloudRain           from './icons/cloud-rain.vue'
import CloudSnow           from './icons/cloud-snow.vue'
import CloudUpload         from './icons/cloud-upload.vue'
import Coins               from './icons/coins.vue'
import Compass             from './icons/compass.vue'
import Container           from './icons/container.vue'
import Copy                from './icons/copy.vue'
import CreditCard          from './icons/credit-card.vue'
import Crosshair           from './icons/crosshair.vue'
import Database            from './icons/database.vue'
import Delete              from './icons/delete.vue'
import Download            from './icons/download.vue'
import Droplet             from './icons/droplet.vue'
import Droplets            from './icons/droplets.vue'
import Earth               from './icons/earth.vue'
import Ellipsis            from './icons/ellipsis.vue'
import EllipsisVertical    from './icons/ellipsis-vertical.vue'
import Eye                 from './icons/eye.vue'
import EyeOff              from './icons/eye-off.vue'
import File                from './icons/file.vue'
import FileCheck           from './icons/file-check.vue'
import FilePlus            from './icons/file-plus.vue'
import FileText            from './icons/file-text.vue'
import FileUp              from './icons/file-up.vue'
import Filter              from './icons/filter.vue'
import FilterX             from './icons/filter-x.vue'
import FingerprintPattern  from './icons/fingerprint-pattern.vue'
import Flag                from './icons/flag.vue'
import Folder              from './icons/folder.vue'
import FolderOpen          from './icons/folder-open.vue'
import Folders             from './icons/folders.vue'
import Globe               from './icons/globe.vue'
import Grip                from './icons/grip.vue'
import Hash                from './icons/hash.vue'
import History             from './icons/history.vue'
import House               from './icons/house.vue'
import IdCard              from './icons/id-card.vue'
import Image               from './icons/image.vue'
import Inbox               from './icons/inbox.vue'
import Info                from './icons/info.vue'
import Key                 from './icons/key.vue'
import KeyRound            from './icons/key-round.vue'
import LandPlot            from './icons/land-plot.vue'
import Languages           from './icons/languages.vue'
import Layers              from './icons/layers.vue'
import LayoutGrid          from './icons/layout-grid.vue'
import Leaf                from './icons/leaf.vue'
import List                from './icons/list.vue'
import ListPlus            from './icons/list-plus.vue'
import LoaderCircle        from './icons/loader-circle.vue'
import Lock                from './icons/lock.vue'
import LockOpen            from './icons/lock-open.vue'
import LogOut              from './icons/log-out.vue'
import Mail                from './icons/mail.vue'
import Map                 from './icons/map.vue'
import MapPin              from './icons/map-pin.vue'
import MapPinned           from './icons/map-pinned.vue'
import Maximize            from './icons/maximize.vue'
import Maximize2           from './icons/maximize-2.vue'
import Menu                from './icons/menu.vue'
import MessageCircleMore   from './icons/message-circle-more.vue'
import MessageSquare       from './icons/message-square.vue'
import Mic                 from './icons/mic.vue'
import Minimize2           from './icons/minimize-2.vue'
import Minus               from './icons/minus.vue'
import MoonStar            from './icons/moon-star.vue'
import MousePointerClick   from './icons/mouse-pointer-click.vue'
import Navigation          from './icons/navigation.vue'
import Package             from './icons/package.vue'
import Palette             from './icons/palette.vue'
import PanelLeft           from './icons/panel-left.vue'
import Pencil              from './icons/pencil.vue'
import Percent             from './icons/percent.vue'
import Phone               from './icons/phone.vue'
import PhoneIncoming       from './icons/phone-incoming.vue'
import PhoneOff            from './icons/phone-off.vue'
import Play                from './icons/play.vue'
import Plus                from './icons/plus.vue'
import QrCode              from './icons/qr-code.vue'
import ReceiptText         from './icons/receipt-text.vue'
import RefreshCcw          from './icons/refresh-ccw.vue'
import RefreshCw           from './icons/refresh-cw.vue'
import RotateCwSquare      from './icons/rotate-cw-square.vue'
import Rows3               from './icons/rows-3.vue'
import Ruler               from './icons/ruler.vue'
import Satellite           from './icons/satellite.vue'
import Save                from './icons/save.vue'
import Scale               from './icons/scale.vue'
import Scan                from './icons/scan.vue'
import ScanLine            from './icons/scan-line.vue'
import ScrollText          from './icons/scroll-text.vue'
import Search              from './icons/search.vue'
import SearchX             from './icons/search-x.vue'
import Send                from './icons/send.vue'
import Settings            from './icons/settings.vue'
import Share2              from './icons/share-2.vue'
import Shield              from './icons/shield.vue'
import ShieldCheck         from './icons/shield-check.vue'
import ShieldOff           from './icons/shield-off.vue'
import SlidersVertical     from './icons/sliders-vertical.vue'
import Smartphone          from './icons/smartphone.vue'
import Sparkle             from './icons/sparkle.vue'
import Sparkles            from './icons/sparkles.vue'
import SprayCan            from './icons/spray-can.vue'
import Sprout              from './icons/sprout.vue'
import SquarePen           from './icons/square-pen.vue'
import Sun                 from './icons/sun.vue'
import SunDim              from './icons/sun-dim.vue'
import Table               from './icons/table.vue'
import Tag                 from './icons/tag.vue'
import Thermometer         from './icons/thermometer.vue'
import ThumbsDown          from './icons/thumbs-down.vue'
import ThumbsUp            from './icons/thumbs-up.vue'
import Tractor             from './icons/tractor.vue'
import Trash               from './icons/trash.vue'
import Trash2              from './icons/trash-2.vue'
import Trees               from './icons/trees.vue'
import TrendingDown        from './icons/trending-down.vue'
import TrendingUp          from './icons/trending-up.vue'
import TriangleAlert       from './icons/triangle-alert.vue'
import Truck               from './icons/truck.vue'
import Undo2               from './icons/undo-2.vue'
import Upload              from './icons/upload.vue'
import User                from './icons/user.vue'
import UserCog             from './icons/user-cog.vue'
import UserMinus           from './icons/user-minus.vue'
import UserPlus            from './icons/user-plus.vue'
import Users               from './icons/users.vue'
import Warehouse           from './icons/warehouse.vue'
import Wheat               from './icons/wheat.vue'
import Wifi                from './icons/wifi.vue'
import WifiOff             from './icons/wifi-off.vue'
import Wind                from './icons/wind.vue'
import X                   from './icons/x.vue'
import Zap                 from './icons/zap.vue'

export const icons = {
  'alarm-clock':            AlarmClock,
  'archive':                Archive,
  'arrow-down':             ArrowDown,
  'arrow-down-left':        ArrowDownLeft,
  'arrow-down-right':       ArrowDownRight,
  'arrow-down-wide-narrow': ArrowDownWideNarrow,
  'arrow-left':             ArrowLeft,
  'arrow-left-right':       ArrowLeftRight,
  'arrow-right':            ArrowRight,
  'arrow-up':               ArrowUp,
  'arrow-up-down':          ArrowUpDown,
  'arrow-up-left':          ArrowUpLeft,
  'arrow-up-narrow-wide':   ArrowUpNarrowWide,
  'arrow-up-right':         ArrowUpRight,
  'badge-check':            BadgeCheck,
  'ban':                    Ban,
  'banknote':               Banknote,
  'bell':                   Bell,
  'bell-off':               BellOff,
  'book-check':             BookCheck,
  'book-open':              BookOpen,
  'box':                    Box,
  'braces':                 Braces,
  'bug':                    Bug,
  'building':               Building,
  'building-2':             Building2,
  'calendar':               Calendar,
  'calendar-days':          CalendarDays,
  'calendar-range':         CalendarRange,
  'camera':                 Camera,
  'chart-column':           ChartColumn,
  'chart-line':             ChartLine,
  'chart-pie':              ChartPie,
  'check':                  Check,
  'chevron-down':           ChevronDown,
  'chevron-left':           ChevronLeft,
  'chevron-right':          ChevronRight,
  'chevron-up':             ChevronUp,
  'chevrons-left':          ChevronsLeft,
  'chevrons-right':         ChevronsRight,
  'chevrons-up-down':       ChevronsUpDown,
  'circle':                 Circle,
  'circle-alert':           CircleAlert,
  'circle-check':           CircleCheck,
  'circle-check-big':       CircleCheckBig,
  'circle-minus':           CircleMinus,
  'circle-play':            CirclePlay,
  'circle-plus':            CirclePlus,
  'circle-question-mark':   CircleQuestionMark,
  'circle-user':            CircleUser,
  'circle-x':               CircleX,
  'clipboard':              Clipboard,
  'clipboard-check':        ClipboardCheck,
  'clipboard-list':         ClipboardList,
  'clock':                  Clock,
  'cloud-download':         CloudDownload,
  'cloud-off':              CloudOff,
  'cloud-rain':             CloudRain,
  'cloud-snow':             CloudSnow,
  'cloud-upload':           CloudUpload,
  'coins':                  Coins,
  'compass':                Compass,
  'container':              Container,
  'copy':                   Copy,
  'credit-card':            CreditCard,
  'crosshair':              Crosshair,
  'database':               Database,
  'delete':                 Delete,
  'download':               Download,
  'droplet':                Droplet,
  'droplets':               Droplets,
  'earth':                  Earth,
  'ellipsis':               Ellipsis,
  'ellipsis-vertical':      EllipsisVertical,
  'eye':                    Eye,
  'eye-off':                EyeOff,
  'file':                   File,
  'file-check':             FileCheck,
  'file-plus':              FilePlus,
  'file-text':              FileText,
  'file-up':                FileUp,
  'filter':                 Filter,
  'filter-x':               FilterX,
  'fingerprint-pattern':    FingerprintPattern,
  'flag':                   Flag,
  'folder':                 Folder,
  'folder-open':            FolderOpen,
  'folders':                Folders,
  'globe':                  Globe,
  'grip':                   Grip,
  'hash':                   Hash,
  'history':                History,
  'house':                  House,
  'id-card':                IdCard,
  'image':                  Image,
  'inbox':                  Inbox,
  'info':                   Info,
  'key':                    Key,
  'key-round':              KeyRound,
  'land-plot':              LandPlot,
  'languages':              Languages,
  'layers':                 Layers,
  'layout-grid':            LayoutGrid,
  'leaf':                   Leaf,
  'list':                   List,
  'list-plus':              ListPlus,
  'loader-circle':          LoaderCircle,
  'lock':                   Lock,
  'lock-open':              LockOpen,
  'log-out':                LogOut,
  'mail':                   Mail,
  'map':                    Map,
  'map-pin':                MapPin,
  'map-pinned':             MapPinned,
  'maximize':               Maximize,
  'maximize-2':             Maximize2,
  'menu':                   Menu,
  'message-circle-more':    MessageCircleMore,
  'message-square':         MessageSquare,
  'mic':                    Mic,
  'minimize-2':             Minimize2,
  'minus':                  Minus,
  'moon-star':              MoonStar,
  'mouse-pointer-click':    MousePointerClick,
  'navigation':             Navigation,
  'package':                Package,
  'palette':                Palette,
  'panel-left':             PanelLeft,
  'pencil':                 Pencil,
  'percent':                Percent,
  'phone':                  Phone,
  'phone-incoming':         PhoneIncoming,
  'phone-off':              PhoneOff,
  'play':                   Play,
  'plus':                   Plus,
  'qr-code':                QrCode,
  'receipt-text':           ReceiptText,
  'refresh-ccw':            RefreshCcw,
  'refresh-cw':             RefreshCw,
  'rotate-cw-square':       RotateCwSquare,
  'rows-3':                 Rows3,
  'ruler':                  Ruler,
  'satellite':              Satellite,
  'save':                   Save,
  'scale':                  Scale,
  'scan':                   Scan,
  'scan-line':              ScanLine,
  'scroll-text':            ScrollText,
  'search':                 Search,
  'search-x':               SearchX,
  'send':                   Send,
  'settings':               Settings,
  'share-2':                Share2,
  'shield':                 Shield,
  'shield-check':           ShieldCheck,
  'shield-off':             ShieldOff,
  'sliders-vertical':       SlidersVertical,
  'smartphone':             Smartphone,
  'sparkle':                Sparkle,
  'sparkles':               Sparkles,
  'spray-can':              SprayCan,
  'sprout':                 Sprout,
  'square-pen':             SquarePen,
  'sun':                    Sun,
  'sun-dim':                SunDim,
  'table':                  Table,
  'tag':                    Tag,
  'thermometer':            Thermometer,
  'thumbs-down':            ThumbsDown,
  'thumbs-up':              ThumbsUp,
  'tractor':                Tractor,
  'trash':                  Trash,
  'trash-2':                Trash2,
  'trees':                  Trees,
  'trending-down':          TrendingDown,
  'trending-up':            TrendingUp,
  'triangle-alert':         TriangleAlert,
  'truck':                  Truck,
  'undo-2':                 Undo2,
  'upload':                 Upload,
  'user':                   User,
  'user-cog':               UserCog,
  'user-minus':             UserMinus,
  'user-plus':              UserPlus,
  'users':                  Users,
  'warehouse':              Warehouse,
  'wheat':                  Wheat,
  'wifi':                   Wifi,
  'wifi-off':               WifiOff,
  'wind':                   Wind,
  'x':                      X,
  'zap':                    Zap,
} as const

export type IconName = keyof typeof icons
